# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salmonellatest',
            name='rawid_many',
            field=models.ManyToManyField(blank=True, related_name='rawid_many', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salmonellatest',
            name='salmonella_many',
            field=models.ManyToManyField(blank=True, related_name='salmonella_many', to=settings.AUTH_USER_MODEL),
        ),
    ]
